import {
  Baby,
  BookOpen,
  Briefcase,
  Building2,
  Camera,
  Car,
  Church,
  ClipboardList,
  Dumbbell,
  Gamepad2,
  Globe,
  GraduationCap,
  Heart,
  House,
  Laptop,
  Lightbulb,
  Music,
  PawPrint,
  Plane,
  Shield,
  ShoppingCart,
  Stethoscope,
  Sun,
  Target,
  Trees,
  Users,
  Utensils,
  Wallet,
  Wrench,
} from "lucide-react";

export const iconMap = {
  heart: Heart,
  dumbbell: Dumbbell,
  briefcase: Briefcase,
  house: House,
  lightbulb: Lightbulb,
  clipboard: ClipboardList,
  users: Users,
  wallet: Wallet,
  car: Car,
  book: BookOpen,
  food: Utensils,
  travel: Plane,
  kids: Baby,
  school: GraduationCap,
  faith: Church,
  security: Shield,
  music: Music,
  photo: Camera,
  tech: Laptop,
  business: Building2,
  outdoors: Trees,
  pets: PawPrint,
  shopping: ShoppingCart,
  repairs: Wrench,
  gaming: Gamepad2,
  world: Globe,
  goals: Target,
  day: Sun,
  medical: Stethoscope,
} as const;

export const iconKeys = Object.keys(iconMap) as Array<keyof typeof iconMap>;